// @keepTs
// @ts-nocheck
export { LicensePlateView } from './src/main/ets/components/LicensePlateView';
export { LicensePlateLetterView } from './src/main/ets/components/LicensePlateLetterView';
export { StockCodeView } from './src/main/ets/components/StockCodeView';
export { EnglishKeyboardView } from './src/main/ets/components/EnglishKeyboardView';
export { KeyBoardManager } from './src/main/ets/utils/KeyBoardManager';
export { openLicensePlate } from './src/main/ets/utils/KeyBoardEx';
