struct preview{build(){Row(){
        Text('<')
          .fontColor('#333333')
          .fontSize(24)
          .fontWeight(500)
        Text('隐私政策')
          .fontColor('#333333')
          .fontSize(24)
          .fontWeight(700)
        Text('     ')
          .fontSize(24)
      }
      .justifyContent(FlexAlign.SpaceAround)
      .width('100%')
      .height(30)
      .padding(1)
      .back}}